name: CRM-Application-Frontend CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - "crm-application-frontend/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "crm-application-frontend/**"

jobs:
  build:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package -f crm-application-frontend

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./crm-application-frontend
        push: true
        tags: mslmtrk/crm-application-frontend:latest
    