name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
    paths:
      - "spring-cloud-config-server/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "spring-cloud-config-server/**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
